const {Router} = require("express")
const {usercreate, login,  index, forms, icontabler, samplepage, uibuttons, uicard, uitypography, loginui, singup, data, resetpassword, otpsend, verify } = require("../controllers/user.logic")
const check = require("../middleware/user.middleware")
const passport = require("passport")
const { finduser, authorize } = require("../middleware/auth")
const router2 = require("./product.routes")
const cat = require("./category.routes")
const subcat = require("./subcategory.route")
const app = Router()
app.get("/" , authorize,index )
app.get("/data" , finduser , data)
app.get("/form", forms)
app.get("/icon-tabler" , icontabler)
app.get("/sample-page" , samplepage)
app.get("/ui-buttons" , uibuttons)
app.get("/ui-card" , uicard)
app.get("/login" , loginui)
app.get("/ui-typography" , uitypography)
app.get("/singup" , singup)
app.post("/singup" ,check , usercreate)
app.post("/login" , passport.authenticate("local") ,login)

app.get("/user" , authorize ,  async(req,res)=>{
    res.send(req.user)
})
app.get("/profile" , (req , res) =>{
    res.render("profile")
})
app.post("/reset",authorize , resetpassword)
app.post("/otp" , otpsend)
app.post("/verify" , verify)

app.use("/product" , router2)
app.use("/category" , cat)
app.use("/subcategory" , subcat)

module.exports = app